# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1

In [4]:
Z = np.zeros(10)
Z[4] = 1

In [6]:
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49

In [8]:
Z = 10 + np.arange(40)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last)

In [9]:
Z = np.arange(40)
Z = Z[::-1]
Z

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Create a 3x3x3 array with random values

In [13]:
Z = np.random.rand(27).reshape(3,3,3)
Z

array([[[0.31688368, 0.01263108, 0.93372408],
        [0.98551879, 0.89992833, 0.42752725],
        [0.22807581, 0.54644845, 0.61864108]],

       [[0.10693951, 0.43718701, 0.85036851],
        [0.14327158, 0.37342902, 0.67104593],
        [0.56004427, 0.14677339, 0.10948344]],

       [[0.86273788, 0.35271512, 0.39628598],
        [0.8967822 , 0.22093141, 0.0344934 ],
        [0.48248992, 0.29082789, 0.67607631]]])

#### 8. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

(0.011517089396724578, 0.9888063767308253)

#### 9. Create a random vector of size 30 and find the mean value

In [1]:
Z = np.random.random(30).mean()
Z

NameError: name 'np' is not defined

#### 10. Create a 2d array with 1 on the border and 0 inside

In [22]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 11. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 12. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 13. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 14. How to round away from zero a float array ?

In [26]:
Z = np.random.uniform(-10,+10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7. 10.  6.  3.  5. -9.  6. -3. -7. -1.]


#### 15. How to find common values between two arrays?

In [27]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 5 6]


#### 16. Is the following expressions true?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/jurajkapasny/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 17. Create a vector of size 10 with values ranging from 0 to 1

In [30]:
Z = np.linspace(0,1,11)
print(Z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### 18. Create a random vector of size 10 and sort it

In [37]:
Z = np.random.random(10)
Z.sort()
Z

array([0.06006243, 0.0872456 , 0.23121848, 0.28816041, 0.29941158,
       0.32773878, 0.4319992 , 0.45491046, 0.75176824, 0.82325485])

#### 19. Consider two random array A and B, check if they are equal

In [32]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)


# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


#### 20. Create random vector of size 10 and replace the maximum value by 0

In [38]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.18129357, 0.        , 0.33654857, 0.31077929, 0.74170034,
       0.13222211, 0.19583832, 0.69050799, 0.19708598, 0.66170347])

#### 21. How to sort an array by the nth column?

In [39]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 9 4]
 [5 6 3]
 [2 4 2]]
[[2 4 2]
 [5 6 3]
 [9 9 4]]


## **Stretch**

This is the final challenge for those who are already familiar with Python or those who finished all the exercises above and are looking for something **more complex**.

### The Monty Hall Problem

Here's a fun and perhaps a surprising statistical riddle and an excellent way to get some practice writing python functions.

In a game show, contestants try to guess which of the three closed doors contain a cash prize (goats are behind the other two doors). Of course, the odds of choosing the correct door are 1 in 3.

However, there is a twist! The host of the show, Mr. Monty Hall, always opens a door after a contestant makes their choice. This door is always one of the two that the contestant did not pick. Behind the opened door, there is a goat. Leaving only two doors unopened, with one of them being the original door that the contestant picked.

Afterwards, the host asks the contestant if they would like to switch their door of choice to the other unopened door. They have the option to keep their original choice or switch to the other unopened door.

The question is, should the contestant switch to the other door? Is there any statistical benefit?

We can answer the problem by running simulations in Python. We'll do it in several parts.

First, write a function called `simulate_prizedoor`. This function will simulate the location of the prize in many games -- see the detailed specification below:

In [41]:

"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print(simulate_prizedoor(3))
array([0, 0, 2])
"""

#your code here
def simulate_prizedoor(nsim):
    return np.random.randint(0, 3, (nsim))

Next, write a function that simulates the contestant's guesses for nsim simulations. Call this function `simulate_guess`. The specs:

In [49]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""
def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int64)

Next, write a function, `goat_door`, to simulate randomly revealing one of the goat doors that a contestant didn't pick.

In [50]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""
#your code here
def goat_door(prizedoors, guesses):
    
    #strategy: generate random answers, and
    #keep updating until they satisfy the rule
    #that they aren't a prizedoor or a guess
    result = np.random.randint(0, 3, prizedoors.size)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum())

Write a function, `switch_guess`, that represents the strategy of always switching a guess after the goat door is opened.

In [51]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""
#your code here
def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 0, (2, 0): 1, (2, 1): 0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)
    return result

The Last function: write a `win_percentage` function that takes an array of guesses and prizedoors, and returns the percent of correct guesses

In [52]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""
#your code here
def win_percentage(guesses, prizedoors):
    return 100 * (guesses == prizedoors).mean()

Now, put it all together. Simulate 10000 games where the contestant keeps their original guess, and 10000 games where the contestant switches their door after the goat door is revealed.

Compute the percentage of time the contestant wins under either strategy. Is one strategy better than the other?

In [53]:
nsim = 10000

#keep guesses
print("Win percentage when keeping original door")
print(win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim)))

#switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd, guess)
guess = switch_guess(guess, goats)
print("Win percentage when switching doors")
print(win_percentage(pd, guess).mean())

Win percentage when keeping original door
33.14
Win percentage when switching doors
65.27


Many people will find this answer counter-intuitive (famously, PhD mathematicians have incorrectly claimed the result must be wrong. Clearly, none of them knew Python).

One of the best ways to build intuition about why opening a goat door affects the odds is to re-run the experiment with 100 doors and one prize. If the game show host opens 98 goat doors after you make your initial selection, would you want to keep your first pick or switch? Can you generalize your simulation code to handle the case with **n** doors?